### ISSUE TITLE
Memory leak with corrupt files 

### ISSUE THREAD

**Issue by mts299** [SuperDARN/rst#254]
I know this is a blacklisted file but this issue is to address potential future files that get through that are corrupt. 

Forgetting the file was a blacklisted file to test pyDARN's IO integrity checks, I tried to make a fitacf file out of it: 
```bash
make_fit 20070117.1001.00.han.rawacf > 20070117.1001.00.han.fitacf
Segmentation fault (core dumped)
```

However, the biggest concern is how it ate up all my computers RAM which is 32 GB :( This froze the machine and if I was running it on my laptop it may have crashed the laptop. So there seems to be a memory leak of some sorts in the code and maybe a nice corrupt file check will save the user distress, time, and potentially losing their machine.

pyDARN returned this error with the file: 
```python
>>> import pydarn 
>>> file = "20070117.1001.00.han.rawacf"
>>> reader = pydarn.DarnRead(file)
>>> reader.read_rawacf()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pydarn-0.1.dev0-py3.6.egg/pydarn/io/superdarn.py", line 394, in read_rawacf
    self._read_darn_records(file_struct_list)
  File "/usr/lib/python3.6/site-packages/pydarn-0.1.dev0-py3.6.egg/pydarn/io/superdarn.py", line 364, in _read_darn_records
    self._read_darn_record(format_fields)
  File "/usr/lib/python3.6/site-packages/pydarn-0.1.dev0-py3.6.egg/pydarn/io/superdarn.py", line 340, in _read_darn_record
    record = self.read_record()
  File "/usr/lib/python3.6/site-packages/pydarn-0.1.dev0-py3.6.egg/pydarn/io/dmap.py", line 453, in read_record
    scalar = self.read_scalar()
  File "/usr/lib/python3.6/site-packages/pydarn-0.1.dev0-py3.6.egg/pydarn/io/dmap.py", line 496, in read_scalar
    self.check_data_type(scalar_type, scalar_name)
  File "/usr/lib/python3.6/site-packages/pydarn-0.1.dev0-py3.6.egg/pydarn/io/dmap.py", line 296, in check_data_type
    self.rec_num)
pydarn.exceptions.dmap_exceptions.DmapDataTypeError: Error: Dmap data type 212 for  at record 263 does not exist in dmap data types.filename: 20070117.1001.00.han.rawacf
```

If anyone is curious about where the problem might be in this file. 

Again I know this is a blacklisted file but for future sake.

**Comment by mts299** [comment]
Not really a fix but improvement with PR #292
